name: user-disable-test
type: wordpress
docroot: web
php_version: "8.0"
webserver_type: nginx-fpm
router_http_port: "8000"
router_https_port: "8443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.5"
nfs_mount_enabled: false
mutagen_enabled: false
hooks:
  post-start:
    # Setup Test Site
    - exec: composer install
    - exec: wp --path=web core install --url=user-disable-test.ddev.site:8443 --title=Test --admin_user=admin1 --admin_password=password --admin_email=admin1@example.com --skip-email
    - exec: wp --path=web plugin activate user-disable

    # Create Test Users
    - exec: wp --path=web user create author1 author1@example.com --role=author --user_pass=password
    - exec: wp --path=web user create admin2 admin2@example.com --role=administrator --user_pass=password
    - exec: wp --path=web user create author2 author2@example.com --role=author --user_pass=password


use_dns_when_possible: true
composer_version: "2"
web_environment:
# Mac/Windows Xdebug Setup
- XDEBUG_CONFIG=mode=debug log=/tmp/xdebug-test.log start_with_request=yes
# Linux Xdebug Setup
#- XDEBUG_CONFIG=mode=debug client_host=172.17.0.1 log=/tmp/xdebug-test.log start_with_request=yes
nodejs_version: "16"
